version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - MA_HOST:db
      - PMA_PORT:3306
      - PMA_ARBITRARY:1
    depends_on:
     - db

  db:
    image: mariadb:10.11.1-rc-jammy
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
       MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mariadb-volume:/data/db
    
networks:
  default:
    name: php-mariadb_network